apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shlomoshalit123/argocd.git
    targetRevision: HEAD
    path: argocd/spring-boot
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true