apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx-ingress
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 1.16.1
    helm:
      releaseName: nginx-ingress
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true